name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.build }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"
          - os: macos-13
            build: "cp38-* cp39-* cp310-*"
          - os: macos-13
            build: "cp311-* cp312-*"
          - os: macos-13
            build: "cp313-* cp314-*"
          - os: macos-latest
            build: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"
          - os: windows-latest
            build: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"
          - os: ubuntu-24.04-arm
            build: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"

    env:
      CIBW_BUILD_VERBOSITY: 1
      CIBW_BUILD: "${{ matrix.build }}"
      CIBW_ARCHS_LINUX: native
      CIBW_SKIP: "*-win32"          # skip all 32-bit CPython on Windows
      # (optionally restrict archs explicitly)
      CIBW_ARCHS_WINDOWS: "AMD64 ARM64"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.21.3

      - name: Build wheels
        run: python -m cibuildwheel --debug-traceback --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      # On tag, upload wheels to PyPI
